### ISSUE TITLE
Invalid recipients

### ISSUE THREAD

**Issue by gerardguiu** [Tigrov/yii2-mailqueue#1]
Hi! 
Is posible to control the errors / exceptions with the invalid recipents?

Exception 'Swift_TransportException' with message 'Expected response code 354 but got code "554", with message "554 5.5.1 Error: no valid recipients

**Comment by Tigrov** [comment]
Hi, you can catch the exception in your code

```php
try {
    $sent = $mailer->send($message);
} catch (Swift_TransportException $e) {
    if (554 == $e->getCode()) {
        // do something
    } else {
        throw $e;
    }
}
```

**Comment by gerardguiu** [comment]
Yes, correct, but you can update the core with this patch? :)
