### ISSUE TITLE
column 'unique_key' used in key specification without a key length

### ISSUE THREAD

**Issue by leonenco** [Tigrov/yii2-mailqueue#2]
```
 > create table {{%mail_queue}} ...Exception 'yii\db\Exception' with message 'SQLSTATE[42000]: Syntax error or access violation: 1170 BLOB/TEXT column 'unique_key' used in key specification without a key length
The SQL being executed was: CREATE TABLE `mail_queue` (
        `id` int(11) NOT NULL AUTO_INCREMENT PRIMARY KEY,
        `unique_key` text NULL DEFAULT NULL UNIQUE,
        `message_data` text NOT NULL,
        `attempts` smallint(6) NOT NULL DEFAULT 0,
        `send_at` datetime(0) NOT NULL DEFAULT now()
) CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE=InnoDB'
```
The solution to the problem is to remove the TEXT or BLOB column from the index or unique constraint or set another field as primary key. If you can't do that, and wanting to place a limit on the TEXT or BLOB column, try to use VARCHAR type and place a limit of length on it. By default, VARCHAR is limited to a maximum of 255 characters and its limit must be specified implicitly within a bracket right after its declaration, i.e VARCHAR(200) will limit it to 200 characters long only.

**Comment by Tigrov** [comment]
Hi, thanks for the report.
